name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

env:
  HF_USERNAME: youtah
  HF_SPACE_NAME: brandboost-content-generator

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Clone Hugging Face Space
      run: |
        # Check if HF token is set
        if [ -z "${{ secrets.HF_TOKEN }}" ]; then
          echo "❌ Error: HF_TOKEN secret is not set"
          echo "Please add your Hugging Face token as a GitHub secret"
          exit 1
        fi
        
        # Clone the space with authentication
        echo "🔄 Cloning space: ${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }}"
        git clone https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }}.git hf-space
        cd hf-space
        git lfs install
        
    - name: Sync files to HF Space
      run: |
        # Copy all files except .git and .github
        rsync -av --exclude='.git' --exclude='.github' --exclude='__pycache__' --exclude='*.pyc' . hf-space/
        
    - name: Commit and push to HF Space
      run: |
        cd hf-space
        git add .
        git commit -m "Auto-sync from GitHub: ${{ github.sha }}" || exit 0
        
        # Push directly with authentication URL
        git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USERNAME }}/${{ env.HF_SPACE_NAME }}.git main
